/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "BuildTbl.h"
#include "unity.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_BuildTbl_PopulatesTable(void);
extern void test_BuildTbl_CorrectValues(void);
extern void test_BuildTbl_EntireTableCorrect(void);
extern void test_BuildTbl_SpecificValues(void);
extern void test_BuildTbl_AlgorithmPattern(void);
extern void test_BuildTbl_PolynomialDefined(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_BuildTbl.c");
  run_test(test_BuildTbl_PopulatesTable, "test_BuildTbl_PopulatesTable", 24);
  run_test(test_BuildTbl_CorrectValues, "test_BuildTbl_CorrectValues", 40);
  run_test(test_BuildTbl_EntireTableCorrect, "test_BuildTbl_EntireTableCorrect", 54);
  run_test(test_BuildTbl_SpecificValues, "test_BuildTbl_SpecificValues", 61);
  run_test(test_BuildTbl_AlgorithmPattern, "test_BuildTbl_AlgorithmPattern", 72);
  run_test(test_BuildTbl_PolynomialDefined, "test_BuildTbl_PolynomialDefined", 82);

  return UNITY_END();
}
